# ADMIN
###
# get all votes
### curl -s http://localhost:8080/rest/admin/vote/getAll --user admin@gmail.com:admin
GET http://localhost:8080/rest/admin/vote/getAll
Authorization: Basic admin@gmail.com admin

###
# get all votes by user id 100001
### curl -s http://localhost:8080/rest/admin/vote/getAll/100001 --user admin@gmail.com:admin
GET http://localhost:8080/rest/admin/vote/getAll/100001
Authorization: Basic admin@gmail.com admin

###
# get vote by id 100012 by user id 100001
### curl -s http://localhost:8080/rest/admin/vote/100001/100012 --user admin@gmail.com:admin
GET http://localhost:8080/rest/admin/vote/100001/100012
Authorization: Basic admin@gmail.com admin

###
# delete vote by id 100012 by user id 100001
### curl -s -X DELETE "http://localhost:8080/rest/admin/vote/100001/100012" --user admin@gmail.com:admin
DELETE http://localhost:8080/rest/admin/vote/100001/100012
Authorization: Basic admin@gmail.com admin

# USER
###
# create vote by restaurant id 100004
### curl -s -X POST "http://localhost:8080/rest/profile/vote?restId=100004" --user user@yandex.ru:password
POST http://localhost:8080/rest/profile/vote?restId=100004
Authorization: Basic user@yandex.ru password

###
# update vote by restaurant id 100004 by vote id 100011 if local time is before 11am
### curl -s -X PUT "http://localhost:8080/rest/profile/vote/100011?restId=100004" --user user@yandex.ru:password
PUT http://localhost:8080/rest/profile/vote/100011?restId=100004
Authorization: Basic user@yandex.ru password


