###
# get all dishes by restaurant id 100002
### curl -s http://localhost:8080/rest/admin/restaurants/100002/dishes --user admin@gmail.com:admin
GET http://localhost:8080/rest/admin/restaurants/100002/dishes
Authorization: Basic admin@gmail.com admin

###
# get dish by id 100007 by restaurant id 100002
### curl -s http://localhost:8080/rest/admin/restaurants/100002/dishes/100007 --user admin@gmail.com:admin
GET http://localhost:8080/rest/admin/restaurants/100002/dishes/100007
Authorization: Basic admin@gmail.com admin

###
# create dish by restaurant id 100002
### curl -s -X POST "http://localhost:8080/rest/admin/restaurants/100002/dishes"
### -H "Content-Type: application/json" -d "{\"name\":\"new dish\",\"price\":1000,\"description\":\"new\"}" --user admin@gmail.com:admin
POST http://localhost:8080/rest/admin/restaurants/100002/dishes
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
  "name": "new dish",
  "price": 1000,
  "description": "new"
}

###
# update dish by id 100007 by restaurant id 100002
### curl -s -X PUT "http://localhost:8080/rest/admin/restaurants/100002/dishes/100007"
### -H "Content-Type: application/json" -d "{\"name\":\"update dish\",\"price\":999,\"description\":\"update\"}" --user admin@gmail.com:admin
PUT http://localhost:8080/rest/admin/restaurants/100002/dishes/100007
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
  "name": "update dish",
  "price": 999,
  "description": "update"
}

###
# delete dish by id 100007 by restaurant id 100002
### curl -s -X DELETE "http://localhost:8080/rest/admin/restaurants/100002/dishes/100007" --user admin@gmail.com:admin
DELETE http://localhost:8080/rest/admin/restaurants/100002/dishes/100007
Authorization: Basic admin@gmail.com admin

###
# get dish not found
### curl -s http://localhost:8080/rest/admin/restaurants/100002/dishes/100015 --user admin@gmail.com:admin
GET http://localhost:8080/rest/admin/restaurants/100002/dishes/100001
Authorization: Basic admin@gmail.com admin



